"""Seed the universities table with a comprehensive directory of Indian HEIs.

Idempotent: skips names already present. Run with:
    python seed_indian_institutions.py
"""
import sys
sys.path.insert(0, r"C:\Users\praji\OneDrive\Desktop\SIH\backend")

from app.core.database import SessionLocal
from app.models.org import University

# (name, state)
INSTITUTIONS = [
    # IITs
    ("Indian Institute of Technology Bombay", "Maharashtra"),
    ("Indian Institute of Technology Delhi", "Delhi"),
    ("Indian Institute of Technology Madras", "Tamil Nadu"),
    ("Indian Institute of Technology Kanpur", "Uttar Pradesh"),
    ("Indian Institute of Technology Kharagpur", "West Bengal"),
    ("Indian Institute of Technology Roorkee", "Uttarakhand"),
    ("Indian Institute of Technology Guwahati", "Assam"),
    ("Indian Institute of Technology Hyderabad", "Telangana"),
    ("Indian Institute of Technology (BHU) Varanasi", "Uttar Pradesh"),
    ("Indian Institute of Technology Indore", "Madhya Pradesh"),
    ("Indian Institute of Technology Ropar", "Punjab"),
    ("Indian Institute of Technology Gandhinagar", "Gujarat"),
    ("Indian Institute of Technology Jodhpur", "Rajasthan"),
    ("Indian Institute of Technology Patna", "Bihar"),
    ("Indian Institute of Technology Bhubaneswar", "Odisha"),
    ("Indian Institute of Technology Mandi", "Himachal Pradesh"),
    ("Indian Institute of Technology Tirupati", "Andhra Pradesh"),
    ("Indian Institute of Technology (ISM) Dhanbad", "Jharkhand"),
    ("Indian Institute of Technology Palakkad", "Kerala"),
    ("Indian Institute of Technology Bhilai", "Chhattisgarh"),
    ("Indian Institute of Technology Goa", "Goa"),
    ("Indian Institute of Technology Jammu", "Jammu & Kashmir"),
    ("Indian Institute of Technology Dharwad", "Karnataka"),
    # NITs
    ("National Institute of Technology Tiruchirappalli", "Tamil Nadu"),
    ("National Institute of Technology Karnataka Surathkal", "Karnataka"),
    ("National Institute of Technology Warangal", "Telangana"),
    ("National Institute of Technology Calicut", "Kerala"),
    ("National Institute of Technology Rourkela", "Odisha"),
    ("National Institute of Technology Jaipur", "Rajasthan"),
    ("National Institute of Technology Nagpur", "Maharashtra"),
    ("National Institute of Technology Kurukshetra", "Haryana"),
    ("Motilal Nehru National Institute of Technology Allahabad", "Uttar Pradesh"),
    ("Maulana Azad National Institute of Technology Bhopal", "Madhya Pradesh"),
    ("National Institute of Technology Durgapur", "West Bengal"),
    ("National Institute of Technology Jamshedpur", "Jharkhand"),
    ("National Institute of Technology Jalandhar", "Punjab"),
    ("National Institute of Technology Hamirpur", "Himachal Pradesh"),
    ("National Institute of Technology Srinagar", "Jammu & Kashmir"),
    ("National Institute of Technology Uttarakhand", "Uttarakhand"),
    ("National Institute of Technology Patna", "Bihar"),
    ("National Institute of Technology Raipur", "Chhattisgarh"),
    ("National Institute of Technology Agartala", "Tripura"),
    ("National Institute of Technology Silchar", "Assam"),
    ("National Institute of Technology Sikkim", "Sikkim"),
    ("National Institute of Technology Meghalaya", "Meghalaya"),
    ("National Institute of Technology Manipur", "Manipur"),
    ("National Institute of Technology Mizoram", "Mizoram"),
    ("National Institute of Technology Nagaland", "Nagaland"),
    ("National Institute of Technology Arunachal Pradesh", "Arunachal Pradesh"),
    ("National Institute of Technology Delhi", "Delhi"),
    ("National Institute of Technology Goa", "Goa"),
    ("National Institute of Technology Puducherry", "Puducherry"),
    ("National Institute of Technology Tadepalligudem", "Andhra Pradesh"),
    ("National Institute of Technology Andhra Pradesh", "Andhra Pradesh"),
    # IIMs
    ("Indian Institute of Management Ahmedabad", "Gujarat"),
    ("Indian Institute of Management Bangalore", "Karnataka"),
    ("Indian Institute of Management Calcutta", "West Bengal"),
    ("Indian Institute of Management Lucknow", "Uttar Pradesh"),
    ("Indian Institute of Management Kozhikode", "Kerala"),
    ("Indian Institute of Management Indore", "Madhya Pradesh"),
    ("Indian Institute of Management Shillong", "Meghalaya"),
    ("Indian Institute of Management Tiruchirappalli", "Tamil Nadu"),
    ("Indian Institute of Management Raipur", "Chhattisgarh"),
    ("Indian Institute of Management Ranchi", "Jharkhand"),
    ("Indian Institute of Management Udaipur", "Rajasthan"),
    ("Indian Institute of Management Kashipur", "Uttarakhand"),
    ("Indian Institute of Management Rohtak", "Haryana"),
    ("Indian Institute of Management Bodh Gaya", "Bihar"),
    ("Indian Institute of Management Jammu", "Jammu & Kashmir"),
    ("Indian Institute of Management Nagpur", "Maharashtra"),
    ("Indian Institute of Management Amritsar", "Punjab"),
    ("Indian Institute of Management Sambalpur", "Odisha"),
    ("Indian Institute of Management Sirmaur", "Himachal Pradesh"),
    ("Indian Institute of Management Visakhapatnam", "Andhra Pradesh"),
    # AIIMS
    ("All India Institute of Medical Sciences New Delhi", "Delhi"),
    ("All India Institute of Medical Sciences Bhopal", "Madhya Pradesh"),
    ("All India Institute of Medical Sciences Bhubaneswar", "Odisha"),
    ("All India Institute of Medical Sciences Jodhpur", "Rajasthan"),
    ("All India Institute of Medical Sciences Patna", "Bihar"),
    ("All India Institute of Medical Sciences Raipur", "Chhattisgarh"),
    ("All India Institute of Medical Sciences Rishikesh", "Uttarakhand"),
    ("All India Institute of Medical Sciences Nagpur", "Maharashtra"),
    ("All India Institute of Medical Sciences Mangalagiri", "Andhra Pradesh"),
    ("All India Institute of Medical Sciences Bibinagar", "Telangana"),
    ("All India Institute of Medical Sciences Gorakhpur", "Uttar Pradesh"),
    ("All India Institute of Medical Sciences Kalyani", "West Bengal"),
    ("All India Institute of Medical Sciences Deoghar", "Jharkhand"),
    ("All India Institute of Medical Sciences Bilaspur", "Himachal Pradesh"),
    ("All India Institute of Medical Sciences Guwahati", "Assam"),
    ("All India Institute of Medical Sciences Jammu", "Jammu & Kashmir"),
    ("All India Institute of Medical Sciences Madurai", "Tamil Nadu"),
    ("All India Institute of Medical Sciences Rajkot", "Gujarat"),
    ("All India Institute of Medical Sciences Bathinda", "Punjab"),
    ("All India Institute of Medical Sciences Raebareli", "Uttar Pradesh"),
    ("All India Institute of Medical Sciences Vijaypur", "Jammu & Kashmir"),
    ("All India Institute of Medical Sciences Awantipora", "Jammu & Kashmir"),
    # IISc
    ("Indian Institute of Science Bangalore", "Karnataka"),
    # IIITs
    ("International Institute of Information Technology Hyderabad", "Telangana"),
    ("Indraprastha Institute of Information Technology Delhi", "Delhi"),
    ("International Institute of Information Technology Bangalore", "Karnataka"),
    ("Indian Institute of Information Technology Allahabad", "Uttar Pradesh"),
    ("Indian Institute of Information Technology Gwalior", "Madhya Pradesh"),
    ("Indian Institute of Information Technology Lucknow", "Uttar Pradesh"),
    ("Indian Institute of Information Technology Jabalpur", "Madhya Pradesh"),
    ("Indian Institute of Information Technology Kancheepuram", "Tamil Nadu"),
    ("Indian Institute of Information Technology Kota", "Rajasthan"),
    ("Indian Institute of Information Technology Sri City", "Andhra Pradesh"),
    ("Indian Institute of Information Technology Nagpur", "Maharashtra"),
    ("Indian Institute of Information Technology Bhagalpur", "Bihar"),
    ("Indian Institute of Information Technology Guwahati", "Assam"),
    ("Indian Institute of Information Technology Kottayam", "Kerala"),
    ("Indian Institute of Information Technology Una", "Himachal Pradesh"),
    ("Indian Institute of Information Technology Bhopal", "Madhya Pradesh"),
    ("Indian Institute of Information Technology Surat", "Gujarat"),
    ("Indian Institute of Information Technology Vadodara", "Gujarat"),
    ("Indian Institute of Information Technology Ranchi", "Jharkhand"),
    ("Indian Institute of Information Technology Dharwad", "Karnataka"),
    ("Indian Institute of Information Technology Kalyani", "West Bengal"),
    ("Indian Institute of Information Technology Manipur", "Manipur"),
    ("Indian Institute of Information Technology Agartala", "Tripura"),
    ("Indian Institute of Information Technology Bhubaneswar", "Odisha"),
    ("Indian Institute of Information Technology Tiruchirappalli", "Tamil Nadu"),
    # Central Universities
    ("University of Delhi", "Delhi"),
    ("University of Mumbai", "Maharashtra"),
    ("University of Madras", "Tamil Nadu"),
    ("University of Calcutta", "West Bengal"),
    ("University of Allahabad", "Uttar Pradesh"),
    ("Banaras Hindu University", "Uttar Pradesh"),
    ("Aligarh Muslim University", "Uttar Pradesh"),
    ("Jawaharlal Nehru University", "Delhi"),
    ("University of Hyderabad", "Telangana"),
    ("Tezpur University", "Assam"),
    ("Assam University", "Assam"),
    ("Central University of Kerala", "Kerala"),
    ("Central University of Rajasthan", "Rajasthan"),
    ("Central University of Haryana", "Haryana"),
    ("Central University of Punjab", "Punjab"),
    ("Central University of Jammu", "Jammu & Kashmir"),
    ("Central University of Kashmir", "Jammu & Kashmir"),
    ("Central University of South Bihar", "Bihar"),
    ("Central University of Gujarat", "Gujarat"),
    ("Dr. Hari Singh Gour University", "Madhya Pradesh"),
    ("Indira Gandhi National Open University", "Delhi"),
    ("Jamia Millia Islamia", "Delhi"),
    ("Guru Ghasidas Vishwavidyalaya", "Chhattisgarh"),
    ("Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya", "Maharashtra"),
    ("North Eastern Hill University", "Meghalaya"),
    ("Pondicherry University", "Puducherry"),
    ("Visva-Bharati", "West Bengal"),
    ("Maulana Azad National Urdu University", "Telangana"),
    ("National Sanskrit University", "Andhra Pradesh"),
    ("English and Foreign Languages University", "Telangana"),
    ("South Asian University", "Delhi"),
    ("Nalanda University", "Bihar"),
    ("Rajiv Gandhi University", "Arunachal Pradesh"),
    ("Manipur University", "Manipur"),
    ("Tripura University", "Tripura"),
    ("Mizoram University", "Mizoram"),
    ("Sikkim University", "Sikkim"),
    ("Nagaland University", "Nagaland"),
    ("Gauhati University", "Assam"),
    ("Dibrugarh University", "Assam"),
    ("Cotton University", "Assam"),
    # State / prominent
    ("Savitribai Phule Pune University", "Maharashtra"),
    ("University of Mysore", "Karnataka"),
    ("Osmania University", "Telangana"),
    ("Anna University", "Tamil Nadu"),
    ("University of Kerala", "Kerala"),
    ("University of Calicut", "Kerala"),
    ("Karnataka University", "Karnataka"),
    ("Bangalore University", "Karnataka"),
    ("Gujarat University", "Gujarat"),
    ("Maharaja Sayajirao University of Baroda", "Gujarat"),
    ("Sardar Patel University", "Gujarat"),
    ("Goa University", "Goa"),
    ("University of Rajasthan", "Rajasthan"),
    ("Mohanlal Sukhadia University", "Rajasthan"),
    ("Jai Narain Vyas University", "Rajasthan"),
    ("Kurukshetra University", "Haryana"),
    ("Panjab University", "Chandigarh"),
    ("Guru Nanak Dev University", "Punjab"),
    ("Punjabi University", "Punjab"),
    ("Himachal Pradesh University", "Himachal Pradesh"),
    ("Kakatiya University", "Telangana"),
    ("Andhra University", "Andhra Pradesh"),
    ("Sri Venkateswara University", "Andhra Pradesh"),
    ("Bharathidasan University", "Tamil Nadu"),
    ("Madurai Kamaraj University", "Tamil Nadu"),
    ("Manonmaniam Sundaranar University", "Tamil Nadu"),
    ("Bharathiar University", "Tamil Nadu"),
    ("Annamalai University", "Tamil Nadu"),
    ("Cochin University of Science and Technology", "Kerala"),
    ("APJ Abdul Kalam Technological University", "Kerala"),
    ("Jadavpur University", "West Bengal"),
    ("Presidency University Kolkata", "West Bengal"),
    ("University of Burdwan", "West Bengal"),
    ("Ranchi University", "Jharkhand"),
    ("Patna University", "Bihar"),
    ("Magadh University", "Bihar"),
    ("Veer Kunwar Singh University", "Bihar"),
    ("Devi Ahilya Vishwavidyalaya", "Madhya Pradesh"),
    ("Rani Durgavati Vishwavidyalaya", "Madhya Pradesh"),
    ("Barkatullah University", "Madhya Pradesh"),
    ("Vikram University", "Madhya Pradesh"),
    ("Jiwaji University", "Madhya Pradesh"),
    ("Sambalpur University", "Odisha"),
    ("Utkal University", "Odisha"),
    ("Berhampur University", "Odisha"),
    ("Fakir Mohan University", "Odisha"),
    ("Gulbarga University", "Karnataka"),
    ("Kuvempu University", "Karnataka"),
    ("Mangalore University", "Karnataka"),
    ("Tumkur University", "Karnataka"),
    ("Davangere University", "Karnataka"),
    ("Swami Ramanand Teerth Marathwada University", "Maharashtra"),
    ("Sant Gadge Baba Amravati University", "Maharashtra"),
    ("Dr. Babasaheb Ambedkar Marathwada University", "Maharashtra"),
    ("Kavayatri Bahinabai Chaudhari North Maharashtra University", "Maharashtra"),
    ("Shivaji University", "Maharashtra"),
    ("Solapur University", "Maharashtra"),
    ("Rashtrasant Tukadoji Maharaj Nagpur University", "Maharashtra"),
    ("Gondwana University", "Maharashtra"),
    ("Chaudhary Charan Singh University", "Uttar Pradesh"),
    ("Chhatrapati Shahu Ji Maharaj University", "Uttar Pradesh"),
    ("University of Lucknow", "Uttar Pradesh"),
    ("Chhatrapati Shahu Ji Maharaj University Kanpur", "Uttar Pradesh"),
    ("Dr. Bhimrao Ambedkar University Agra", "Uttar Pradesh"),
    ("MJP Rohilkhand University", "Uttar Pradesh"),
    ("Veer Bahadur Singh Purvanchal University", "Uttar Pradesh"),
    ("Bundelkhand University", "Uttar Pradesh"),
    ("Dr. Ram Manohar Lohia Avadh University", "Uttar Pradesh"),
    ("Deen Dayal Upadhyay Gorakhpur University", "Uttar Pradesh"),
    ("Saurashtra University", "Gujarat"),
    ("Bhavnagar University", "Gujarat"),
    ("Junagadh Agricultural University", "Gujarat"),
    ("Gujarat Technological University", "Gujarat"),
    ("Maharishi Dayanand University", "Haryana"),
    ("Chaudhary Devi Lal University", "Haryana"),
    ("Baba Farid University of Health Sciences", "Punjab"),
    ("Tamil Nadu Agricultural University", "Tamil Nadu"),
    ("Periyar University", "Tamil Nadu"),
    ("Thiruvalluvar University", "Tamil Nadu"),
    # Prominent private / deemed
    ("Birla Institute of Technology and Science Pilani", "Rajasthan"),
    ("Birla Institute of Technology and Science Hyderabad", "Telangana"),
    ("Birla Institute of Technology and Science Goa", "Goa"),
    ("Vellore Institute of Technology", "Tamil Nadu"),
    ("VIT-AP University", "Andhra Pradesh"),
    ("Manipal Academy of Higher Education", "Karnataka"),
    ("SRM Institute of Science and Technology", "Tamil Nadu"),
    ("Amrita Vishwa Vidyapeetham", "Tamil Nadu"),
    ("Thapar Institute of Engineering and Technology", "Punjab"),
    ("Birla Institute of Technology Mesra", "Jharkhand"),
    ("SASTRA University", "Tamil Nadu"),
    ("Karunya Institute of Technology and Sciences", "Tamil Nadu"),
    ("Kalinga Institute of Industrial Technology", "Odisha"),
    ("Siksha 'O' Anusandhan", "Odisha"),
    ("Bharati Vidyapeeth", "Maharashtra"),
    ("Symbiosis International University", "Maharashtra"),
    ("Christ University", "Karnataka"),
    ("Jain University", "Karnataka"),
    ("Alliance University", "Karnataka"),
    ("Acharya Nagarjuna University", "Andhra Pradesh"),
    ("GITAM University", "Andhra Pradesh"),
    ("Koneru Lakshmaiah Education Foundation", "Andhra Pradesh"),
    ("Vel Tech University", "Tamil Nadu"),
    ("Hindustan Institute of Technology and Science", "Tamil Nadu"),
    ("REVA University", "Karnataka"),
    ("Amity University Noida", "Uttar Pradesh"),
    ("Amity University Kolkata", "West Bengal"),
    ("Sharda University", "Uttar Pradesh"),
    ("Galgotias University", "Uttar Pradesh"),
    ("NIIT University", "Rajasthan"),
    ("Lovely Professional University", "Punjab"),
    ("Chandigarh University", "Punjab"),
    ("Chitkara University", "Punjab"),
    ("Graphic Era University", "Uttarakhand"),
    ("DIT University", "Uttarakhand"),
    ("University of Petroleum and Energy Studies", "Uttarakhand"),
    ("MIT World Peace University", "Maharashtra"),
    ("MIT Art, Design and Technology University", "Maharashtra"),
    ("Saveetha Institute of Medical and Technical Sciences", "Tamil Nadu"),
    ("Shiv Nadar University", "Uttar Pradesh"),
    ("Kalasalingam Academy of Research and Education", "Tamil Nadu"),
    ("PSNA College of Engineering and Technology", "Tamil Nadu"),
]


def main():
    db = SessionLocal()
    existing = {u.name for u in db.query(University.name).all()}
    added = 0
    for name, state in INSTITUTIONS:
        if name in existing:
            continue
        db.add(University(name=name, state=state, verified=True))
        existing.add(name)
        added += 1
    db.commit()
    total = db.query(University).count()
    db.close()
    print(f"Added {added} new institutions. Total in directory: {total}")


if __name__ == "__main__":
    main()
