"""add classification_feedback and classification_metrics tables

Revision ID: 54bf0cd773ad
Revises: f101b5ced202
Create Date: 2026-09-03 19:43:27.403579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54bf0cd773ad'
down_revision: Union[str, Sequence[str], None] = 'f101b5ced202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_metrics',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.String(length=100), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('total_predictions', sa.Integer(), nullable=False),
    sa.Column('correct_predictions', sa.Integer(), nullable=False),
    sa.Column('user_corrections', sa.Integer(), nullable=False),
    sa.Column('priority_accuracy', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_metrics_category_id'), 'classification_metrics', ['category_id'], unique=False)
    op.create_table('classification_feedback',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('problem_id', sa.String(length=20), nullable=False),
    sa.Column('ai_category_id', sa.String(length=100), nullable=True),
    sa.Column('ai_category_name', sa.String(length=100), nullable=True),
    sa.Column('ai_tags', sa.JSON(), nullable=True),
    sa.Column('ai_priority', sa.String(length=20), nullable=True),
    sa.Column('corrected_category_id', sa.String(length=100), nullable=False),
    sa.Column('corrected_category_name', sa.String(length=100), nullable=False),
    sa.Column('corrected_tags', sa.JSON(), nullable=True),
    sa.Column('corrected_priority', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('is_correction', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_feedback_problem_id'), 'classification_feedback', ['problem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classification_feedback_problem_id'), table_name='classification_feedback')
    op.drop_table('classification_feedback')
    op.drop_index(op.f('ix_classification_metrics_category_id'), table_name='classification_metrics')
    op.drop_table('classification_metrics')
    # ### end Alembic commands ###