""" phase1_3_schema

Revision ID: 877c640c9f15
Revises: 
Create Date: 2026-08-27 19:25:43.579779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '877c640c9f15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'UNIVERSITY_ADMIN', 'STUDENT', 'FACULTY', 'INDUSTRY', 'GOVERNMENT', 'ADMIN', name='role_enum'), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('domain_tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('PROBLEM_ROUTED', 'PROPOSAL_RECEIVED', 'STATUS_UPDATED', 'DUPLICATE_FLAGGED', 'GENERIC', name='notification_type_enum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.String(length=20), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_urls', sa.JSON(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('ai_tags', sa.JSON(), nullable=True),
    sa.Column('ai_category', sa.String(length=100), nullable=True),
    sa.Column('ai_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority_enum'), nullable=True),
    sa.Column('ai_duplicate_check', sa.Boolean(), nullable=True),
    sa.Column('ai_duplicate_of', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('PENDING_VALIDATION', 'VALIDATED', 'REJECTED', 'DUPLICATE', 'OPEN', 'IN_REVIEW', 'PROPOSAL_SUBMITTED', 'IN_COLLABORATION', 'PROTOTYPE', 'PILOT', 'IMPLEMENTED', 'CLOSED', name='problem_status_enum'), nullable=False),
    sa.Column('assigned_to_id', sa.String(length=20), nullable=True),
    sa.Column('submitter_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('problem_id', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT', 'TEXT', name='evidence_type_enum'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_problem_id'), 'evidence', ['problem_id'], unique=False)
    op.create_table('problem_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_id', sa.String(length=20), nullable=False),
    sa.Column('tag_id', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'tag_id', name='uq_problem_tag')
    )
    op.create_index(op.f('ix_problem_tags_problem_id'), 'problem_tags', ['problem_id'], unique=False)
    op.create_index(op.f('ix_problem_tags_tag_id'), 'problem_tags', ['tag_id'], unique=False)
    op.create_table('routing_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_id', sa.String(length=20), nullable=False),
    sa.Column('routed_to_type', sa.Enum('UNIVERSITY', 'INDUSTRY', name='routing_type_enum'), nullable=False),
    sa.Column('routed_to_id', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['routed_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_logs_problem_id'), 'routing_logs', ['problem_id'], unique=False)
    op.create_index(op.f('ix_routing_logs_routed_to_id'), 'routing_logs', ['routed_to_id'], unique=False)
    op.create_table('solutions',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('approach', sa.Text(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('estimated_timeline', sa.String(length=100), nullable=True),
    sa.Column('estimated_budget', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', name='solution_status_enum'), nullable=False),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('demo_url', sa.String(length=500), nullable=True),
    sa.Column('document_urls', sa.JSON(), nullable=True),
    sa.Column('problem_id', sa.String(length=20), nullable=False),
    sa.Column('author_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solutions')
    op.drop_index(op.f('ix_routing_logs_routed_to_id'), table_name='routing_logs')
    op.drop_index(op.f('ix_routing_logs_problem_id'), table_name='routing_logs')
    op.drop_table('routing_logs')
    op.drop_index(op.f('ix_problem_tags_tag_id'), table_name='problem_tags')
    op.drop_index(op.f('ix_problem_tags_problem_id'), table_name='problem_tags')
    op.drop_table('problem_tags')
    op.drop_index(op.f('ix_evidence_problem_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_table('problems')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
